### ISSUE TITLE
BuildKit broken since 0.71 with multiple project solutions

### ISSUE THREAD

**Issue by mylesmacrae** [batect/batect#970]
### Describe the bug

When building and running a dotnet core application with multiple project via a dockerfile using buildkit, an error is generated by batect from the new FileSyncService.  Running it multiple times with no change produces different messages in some cases.   Removing the sub project allows it to build.

``` 
PS C:\dev\batecttest\0.71> .\batect start
Version 0.72.0 of Batect is now available (you have 0.71.0).
To upgrade to the latest version, run './batect --upgrade'.
For more information, visit https://github.com/batect/batect/releases/tag/0.72.0.

Running start...
helloworld: building image: [internal] load build context

Error: Could not build image for container helloworld.
Building image failed: changes out of order: "testproj/Program.cs" "testproj.sub". Output from build process was:
#1 [internal] load build definition from Dockerfile
#1 ...

#2 [internal] load .dockerignore

#1 [internal] load build definition from Dockerfile
#1 transferring dockerfile:: done
#1 ...

#2 [internal] load .dockerignore
#2 transferring context:: done
#2 ...

#1 [internal] load build definition from Dockerfile
#1 DONE

#2 [internal] load .dockerignore
#2 DONE

#3 [internal] load metadata for mcr.microsoft.com/dotnet/sdk:3.1-alpine
#3 DONE

#4 [1/6] FROM mcr.microsoft.com/dotnet/sdk:3.1-alpine
#4 ...

#5 [internal] load build context
#5 transferring context:: done
#5 ERROR: changes out of order: "testproj/Program.cs" "testproj.sub"

Clean up: done

The task start failed. See above for details.
PS C:\dev\batecttest\0.71> .\batect start
Version 0.72.0 of Batect is now available (you have 0.71.0).
To upgrade to the latest version, run './batect --upgrade'.
For more information, visit https://github.com/batect/batect/releases/tag/0.72.0.

Running start...
helloworld: building image: [internal] load build context

Error: Could not build image for container helloworld.
1 exception(s) thrown during image build:
Exception #1: batect.docker.DockerException: Received error message from daemon during file sync: context canceled
        at batect.docker.build.buildkit.services.FileSyncService.access$handleIncomingRequests(FileSyncService.kt:75)
        at batect.docker.build.buildkit.services.FileSyncService$DiffCopy$1$2.invokeSuspend(FileSyncService.kt:105)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
        Suppressed: okhttp3.internal.http2.StreamResetException: stream was reset: CANCEL
                at okhttp3.internal.http2.Http2Stream.checkOutNotClosed$okhttp(Http2Stream.kt:648)
                at okhttp3.internal.http2.Http2Stream$FramingSink.flush(Http2Stream.kt:579)
                at okio.RealBufferedSink.flush(RealBufferedSink.kt:269)
                at com.squareup.wire.internal.GrpcMessageSink.write(GrpcMessageSink.kt:51)
                at batect.docker.build.buildkit.services.FileSyncService$SynchronisedMessageSink.write(FileSyncService.kt:256)
                at batect.docker.build.buildkit.services.FileSyncService.sendFileContents(FileSyncService.kt:196)
                at batect.docker.build.buildkit.services.FileSyncService.handleFileRequests(FileSyncService.kt:171)
                at batect.docker.build.buildkit.services.FileSyncService.access$handleFileRequests(FileSyncService.kt:75)
                at batect.docker.build.buildkit.services.FileSyncService$handleFileRequests$1.invokeSuspend(FileSyncService.kt)
                ... 5 more




Clean up: done

The task start failed. See above for details.
```

### Reproduction repo

https://github.com/mylesmacrae/batect-bug

### Steps to reproduce

Make sure build kit is enabled ( `setx DOCKER_BUILDKIT 1` , `--enable-buildkit` or otherwise)
download the repro project
run `.\batect start`

### Expected behaviour

container builds and runs with an output of `startup`.   

Here is output from manual docker run:

```
PS C:\dev\batecttest\0.71> docker build --no-cache -f project/Dockerfile -t test project
[+] Building 4.5s (11/11) FINISHED
 => [internal] load build definition from Dockerfile                                                               0.0s
 => => transferring dockerfile: 32B                                                                                0.0s
 => [internal] load .dockerignore                                                                                  0.0s
 => => transferring context: 35B                                                                                   0.0s
 => [internal] load metadata for mcr.microsoft.com/dotnet/sdk:3.1-alpine                                           0.0s
 => [1/6] FROM mcr.microsoft.com/dotnet/sdk:3.1-alpine                                                             0.0s
 => [internal] load build context                                                                                  0.0s
 => => transferring context: 230B                                                                                  0.0s
 => CACHED [2/6] WORKDIR /src                                                                                      0.0s
 => [3/6] COPY . .                                                                                                 0.0s
 => [4/6] WORKDIR /src/testproj                                                                                    0.0s
 => [5/6] RUN dotnet publish testproj.csproj -c Release  -o /app                                                   4.1s
 => [6/6] WORKDIR /app                                                                                             0.0s
 => exporting to image                                                                                             0.1s
 => => exporting layers                                                                                            0.1s
 => => writing image sha256:f25ac7830faf538588fbf49fcac5c3c120b0e4e783e2e8325f39a6d8feaf4ea3                       0.0s
 => => naming to docker.io/library/test                                                                            0.0s

Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them
PS C:\dev\batecttest\0.71> docker run -t test
startup
```

### Actual behaviour

``` 
PS C:\dev\batecttest\0.71> .\batect start
Version 0.72.0 of Batect is now available (you have 0.71.0).
To upgrade to the latest version, run './batect --upgrade'.
For more information, visit https://github.com/batect/batect/releases/tag/0.72.0.

Running start...
helloworld: building image: [internal] load build context

Error: Could not build image for container helloworld.
Building image failed: changes out of order: "testproj/Program.cs" "testproj.sub". Output from build process was:
#1 [internal] load build definition from Dockerfile
#1 ...

#2 [internal] load .dockerignore

#1 [internal] load build definition from Dockerfile
#1 transferring dockerfile:: done
#1 ...

#2 [internal] load .dockerignore
#2 transferring context:: done
#2 ...

#1 [internal] load build definition from Dockerfile
#1 DONE

#2 [internal] load .dockerignore
#2 DONE

#3 [internal] load metadata for mcr.microsoft.com/dotnet/sdk:3.1-alpine
#3 DONE

#4 [1/6] FROM mcr.microsoft.com/dotnet/sdk:3.1-alpine
#4 ...

#5 [internal] load build context
#5 transferring context:: done
#5 ERROR: changes out of order: "testproj/Program.cs" "testproj.sub"

Clean up: done

The task start failed. See above for details.
PS C:\dev\batecttest\0.71> .\batect start
Version 0.72.0 of Batect is now available (you have 0.71.0).
To upgrade to the latest version, run './batect --upgrade'.
For more information, visit https://github.com/batect/batect/releases/tag/0.72.0.

Running start...
helloworld: building image: [internal] load build context

Error: Could not build image for container helloworld.
1 exception(s) thrown during image build:
Exception #1: batect.docker.DockerException: Received error message from daemon during file sync: context canceled
        at batect.docker.build.buildkit.services.FileSyncService.access$handleIncomingRequests(FileSyncService.kt:75)
        at batect.docker.build.buildkit.services.FileSyncService$DiffCopy$1$2.invokeSuspend(FileSyncService.kt:105)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
        Suppressed: okhttp3.internal.http2.StreamResetException: stream was reset: CANCEL
                at okhttp3.internal.http2.Http2Stream.checkOutNotClosed$okhttp(Http2Stream.kt:648)
                at okhttp3.internal.http2.Http2Stream$FramingSink.flush(Http2Stream.kt:579)
                at okio.RealBufferedSink.flush(RealBufferedSink.kt:269)
                at com.squareup.wire.internal.GrpcMessageSink.write(GrpcMessageSink.kt:51)
                at batect.docker.build.buildkit.services.FileSyncService$SynchronisedMessageSink.write(FileSyncService.kt:256)
                at batect.docker.build.buildkit.services.FileSyncService.sendFileContents(FileSyncService.kt:196)
                at batect.docker.build.buildkit.services.FileSyncService.handleFileRequests(FileSyncService.kt:171)
                at batect.docker.build.buildkit.services.FileSyncService.access$handleFileRequests(FileSyncService.kt:75)
                at batect.docker.build.buildkit.services.FileSyncService$handleFileRequests$1.invokeSuspend(FileSyncService.kt)
                ... 5 more




Clean up: done

The task start failed. See above for details.
```

### Version information

```plain text
PS C:\dev\batecttest\0.71> .\batect --version
Batect version:    0.71.0
Built:             2021-07-22 12:00:56 +0000
Built from commit: 36a6a79c7338025c30b9b7e4a857380d28086ff4 (commit date: 2021-07-22 21:28:32 +1000)
JVM version:       AdoptOpenJDK OpenJDK 64-Bit Server VM 11.0.4
OS version:        Windows 10 10.0 amd64
Docker version:    20.10.8 (API version: 1.41, minimum supported API version: 1.12, commit: 75249d8, operating system: 'linux', experimental: false)
Git version:       2.30.1.windows.1

For documentation and further information on Batect, visit https://github.com/batect/batect.

Version 0.72.0 of Batect is now available (you have 0.71.0).
To upgrade to the latest version, run './batect --upgrade'.
For more information, visit https://github.com/batect/batect/releases/tag/0.72.0.
```

I have tested with `0.72.0`.  Same results.
```


### Any other information

_No response_

**Comment by mylesmacrae** [comment]
With build kit disabled, the task runs successfully:

```
PS C:\dev\batecttest\0.71> .\batect start
Version 0.72.0 of Batect is now available (you have 0.71.0).
To upgrade to the latest version, run './batect --upgrade'.
For more information, visit https://github.com/batect/batect/releases/tag/0.72.0.

Running start...
helloworld: running

startup

start finished with exit code 0 in 7.1s.
```

**Comment by charleskorn** [comment]
Thanks for the detailed report and for providing a damper project @mylesmacrae. I've been out sick but I will take a look at this as soon as I can.

**Comment by charleskorn** [comment]
I've just fixed this and I'll release a new version shortly. Thanks again for the bug report @mylesmacrae!
